const menuImages={
    featureImage:require("./feature-selected-image.svg").default,
    featureImageUnselected:require("./feature-unselected-image.svg").default,
    industrySelected:require("./industry-selected.svg").default,
    industryUnSelected:require("./industry-unselected-image.svg").default,
    newStorySelected:require("./news-stories-selected.svg").default,
    newStoryUnSelected:require("./new-stories-unselected.svg").default,
    aboutSelected:require("./about-selected.svg").default,
    aboutUnselected:require("./about-unselected.svg").default,
    unselectedLegal:require("./unselected-legal.svg").default,
    unselectedResources:require("./unselected-resources.svg").default,
    unselectedSales:require('./unselected-feature-sales.svg').default,
    unselectedWatchDemo:require('./unselected-watch-demo.svg').default,
    meMateCheck:require("./memate-check.svg").default,
    RequestAdemo:require('./request-a-demo.svg').default,
    clientManagement:require("./client-management.svg").default,
    supplierManagement:require("./supplier-management.svg").default,
    salesPipeline:require("./sales-pipeline.svg").default,
    projectManagement:require("./project-management.svg").default,
    jobApproval: require("./job-approval.svg").default,
    MultiLocation: require("./multi-location.svg").default,
    Calculators: require("./calculators.svg").default,
    internalChat:require("./internal-chat.svg").default,
    timeSheet:require("./timsheet.svg").default,
    news:require("./news.svg").default,
    taskManagement:require("./task-management.svg").default,
    reports:require('./reports.svg').default,
    profitAndBudget:require("./profitability-budgetinh.svg").default,
    emplyManage:require('./empma.svg').default,
    contractor:require('./contractor.svg').default,
    communication:require("./communication.svg").default,
    schduling:require("./schduleing.svg").default,
    invoicing:require("./invoiving.svg").default,
    statistics:require('./statistics.svg').default,
    jobSchdule:require('./job-schule.svg').default,
    jobHouly:require('./job-hourly.svg').default,
    calendar:require('./calendar.svg').default,
    creativeAgency:require('./creative-agencies.svg').default,
    electronic:require("./electronic.svg").default,
    photoVideoAgency:require("./photo-video-agency.svg").default,
    automotive:require("./automotive.svg").default,
    startUps:require("./startups.svg").default,
    construction:require("./construction.svg").default,
    selectedLegal:require("./selected-legal.svg").default,
    selectedResources:require("./selected-ressources.svg").default
}

export default menuImages;