const Images = {
  landingHero: require("./Web.svg"),
  logo: require("./logo.svg").default,
  BurgerIcon: require("./burger-menu-svgrepo-com.svg").default,
  burgerCloseIcon: require("./burger-close-icon.svg").default,
  macLeptop:require('./mackook-image.svg').default,
  iphone:require('./iphone-image.svg').default,
  rightImage:require('./task-image-create.svg').default,
  metricItem:require('./metric-image.svg').default,
  skyNews:require('./sky-news.svg').default,
  theAustralian:require('./the-australian.svg').default,
  abc:require('./abc.svg').default,
  cameraFix: require('./camera-fix.svg').default,
  owners:require('./owners.svg').default,
  owners_card:require("./card1.svg").default,
  business:require('./business.svg').default,
  industries:require('./industries.svg').default,
  macWithIphone:require('./iPhone-with-mockup.svg').default,
  boostImage:require('./boast-image.svg').default,
  xeroBrand:require('./xero.svg').default,
  amazonBrand:require('./bg-amazon.png'),
  underStand:require('./understand.svg').default,
  zeroScreenShot:require('./zero-onboarding.svg').default,
  asanaBrand:require('./asana.svg').default,
  myobBrand:require('./myob.svg').default,
  metaBradnLogo:require('./brand-meta-logo.svg').default,
  stripeBrand:require('./stripe.svg').default,
  googleAnalyticsBrand:require('./goolge-anolytics.svg').default,
  paypolBrand:require('./pay-pol.svg').default,
  googleBrand:require('./google-brand.svg').default,
  popup:require('./Popup.svg').default,
  maxImage:require('./max-image-1.svg').default,
  sales:require('./sales.svg').default,
  financeImage:require('./insight-image.svg').default,
  salesBg:require('./sales-bg.png'),
  menuItem:require('./menu-items.png'),
  getPayment:require('./get-payment.png'),
  defoultState:require('./default-state.png'),
  modal:require('./modal-popup.png'),
  quote:require("./quote.svg").default,
  profitability:require('./profitablity.svg').default,
  management:require('./management.svg').default,
  communication:require('./communication.svg').default,
  reporting:require('./reporting.svg').default,
  theGuardian:require('./the-guardian.svg').default,
  quoteBg:require('./quote-bg.png'),
  appStore:require("./app-store.svg").default,
  calculation:require('./calculation.svg').default,
  employees:require('./employees.svg').default,
  sendMsgModal:require('./send-sms-modal.png'),
  timeLine:require('./timeline-image.svg').default,
  taskDetails:require('./task-details.svg').default,
  cardBg:require('./card-bg.png'),
  note:require('./note.svg').default,
  saleActive: require('../icons/sale-active.svg').default,
  quoteActive: require('../icons/quote-active.svg').default,
  profitabilityActive: require("../icons/profitability-active.svg").default,
  managmentActive: require("../icons/management-active.svg").default,
  reportingActive: require("../icons/reporting-active.svg").default,
  communicationActive: require("../icons/communication-active.svg").default,
  calculationActive: require("../icons/calculation-active.svg").default,
  schedulingActive: require("../icons/scheduling-active.svg").default,
  employeeActive: require("../icons/employees-active.svg").default,
  emptyWallet:require('./empty-wallet.svg').default,
  shopicon:require('./shop.svg').default,
  mask:require('./mask.svg').default,
  graphBuss:require('./graph-bussiness.svg').default,
  suppliers:require('./suppliers.svg').default,
  graphAndNum:require('./graph-and-number.svg').default,
  busprofile:require('./man.svg').default,
  calender:require('./calendar-tick.svg').default,
  metalogo:require('./me-meta-log.svg').default,
  iconWork:require('./icon-work.svg').default,
  iconDashb:require('./icon-dashboard.svg').default,
  graph:require('./graph.svg').default,
  iconApproval:require('./icon-approval.svg').default,
  iconPople:require('./icon-people.svg').default,
  textImage:require('./create-new-task.svg').default,
  exportTag:require('./tag-export.svg').default,
  profileUser:require('./profile-user.svg').default,
  capture:require('./capture.png'),
  moneyVariation:require('./money-variation.png'),
  defoultImage:require('./default-image.png'),
  aboutBgGrid:require('./aboutBgGrid.png'),
  aboutBgGrid1:require('./aboutBgGrid1.png'),
  captureDeecran:require('./capture_d_écran.png'),
  backgroundPattern:require('./background-pattern.png'),
  comingsoonPic:require('./comingsoonPic.png'),
  PngwingPic:require('./pngwing.png'),
  koalaTransparent:require('./koala-transparent.png'),
  historyDate:require('./history-date.png'),
  datePicker:require('./date-picker-menu.png'),
  dashboard:require('./dashboard.png'),
  quotationAns:require('./quotation-ans.png'),
  mergeItems:require('./merge-Items.png'),
  editModalItem:require('./Edit-Merged-Items.png'),
  metricItemReporting:require('./metric-item-reporting.png'),
  modalMessages:require('./modal-messages.png'),
  modalReporing:require('./modal-reporing.png'),
  reportingBg:require('./reporting-bg.png'),
  paymentModal:require('./modal-confirm-payment.png'),
  scheduling:require('./scheduling.svg').default,
  googleStore:require("./google-store.svg").default,
  macAppStore:require("./mac-app-store.svg").default,
  microSoftSore:require("./microsoft.svg").default,
  facebookIcon:require("./facebook-Icon.svg").default,
  instagramIcon:require("./instagram.svg").default,
  linkdinIcon:require("./linkdin.svg").default,
  macBook:require('./macbook-mock-up.svg').default,
  leadsTable:require("./leads-table.svg").default,
  ClientTable:require("./client-table.svg").default,
  SupplierTable:require("./supplier-table.svg").default,
  ModalSaleContact:require("./Modal-Sales-Contact.svg").default,
  ClientRelationship:require("./client-relationship.svg").default,
  HelpfullSupplier:require("./helpfull-supplier.svg").default,
  MenuContact:require("./Menu.svg").default,
  pipeLine:require("./pipelinie-menu.svg").default,
  filterPipeline:require("./filter-pipeline.svg").default,
  ClientBusiness:require("./client-business.svg").default,
  ContactSupplier:require("./contact-supplier.svg").default,
  salesProtestOptimization:require("./sales-protest-optimization.svg").default,
  ClientHistory:require("./client-history.svg").default,
  Insightful:require("./insightful.svg").default,
  pipeLineManagement:require("./pipeline-management.svg").default,
  ClientInformation:require("./client-information.svg").default,
  OrderHistory:require("./order-history.svg").default,
  suitableMenu:require("./suitable-menu.svg").default,
  suitableImage:require("./suitable-temp.svg").default,
  SupplierReport:require("./supplier-report.svg").default,
  investmentIcon:require("./investment-icon.svg").default,
  selectedQuestion:require("./plus-question-icon.svg").default
};

export default Images;
